install.packages("magrittr")
install.packages("tm")
install.packages("word2vec")
install.packages("XML")
install.packages("qdap")
install.packages("lumberjack")
install.packages("readtext")
remotes::install_github("bnosac/word2vec") 
